AWSTemplateFormatVersion: 2010-09-09
Ressources:
    S3Bucket:
        Type: 'AWS::S3::Bucket'
        DeletionPolicy: Retain
        Properties:
            BucketName: STD21001
            AccessControl: PublicRead
    BucketSSM:
      Type: AWS::SSM::Parameter
      Properties:
        Name: Bucket AccessControl
        Type: String

